AI_ENABLED: true
AVAILABLE_VISION_MODELS:
- Qwen/Qwen2.5-VL-32B-Instruct
- Pro/Qwen/Qwen2.5-VL-7B-Instruct
DB_PATH: ./data/db/smartimagefinder.db
DESCRIPTION_INDEX_PATH: ./data/faiss/description_vectors.faiss
HOST: 0.0.0.0
PORT: 1000
IMAGE_INDEX_PATH: ./data/faiss/image_vectors.faiss
IMAGE_VECTOR_CACHE_DIR: ./data/caches/image_vector_cache
MAX_CACHE_SIZE_GB: 1.5
MODEL_PATH: jina-clip-v2 # 推荐自己下载模型并把路径放在这里
OPENAI_API_BASE: https://api.siliconflow.cn/v1
OPENAI_API_KEY: sk-
TEXT_VECTOR_CACHE_DIR: ./data/caches/text_vector_cache
TITLE_INDEX_PATH: ./data/faiss/title_vectors.faiss
UPLOAD_DIR: ./data/images
USE_CACHE: true
UUID_MAP_PATH: ./data/faiss/uuid_map.pickle
VECTOR_DIM: 1024
VISION_MODEL: Qwen/Qwen2.5-VL-32B-Instruct
