AVAILABLE_VISION_MODELS:
- Qwen/Qwen2.5-VL-32B-Instruct
- Pro/Qwen/Qwen2.5-VL-7B-Instruct
DB_PATH: ./data/db/smartimagefinder.db
DESCRIPTION_INDEX_PATH: ./data/faiss/description_vectors.faiss
HOST: 0.0.0.0
PORT: 1000
IMAGE_INDEX_PATH: ./data/faiss/image_vectors.faiss
IMAGE_VECTOR_CACHE_DIR: ./data/caches/image_vector_cache
MAX_CACHE_SIZE_GB: 1.5
MODEL_PATH: jina-clip-v2 # 推荐自己下载模型并把路径放在这里
EMBEDDING_DIMENSION: 1024
OPENAI_API_BASE: https://api.siliconflow.cn/v1 # 请根据需要修改API基础地址
OPENAI_API_KEY: "" # 请在这里填写你的API密钥
TEXT_VECTOR_CACHE_DIR: ./data/caches/text_vector_cache
TEMP_FILES_DIR: ./data/temp_files
TITLE_INDEX_PATH: ./data/faiss/title_vectors.faiss
UPLOAD_DIR: ./data/images
TEMP_DIR: ./data/temp
USE_CACHE: true
UUID_MAP_PATH: ./data/faiss/uuid_map.pickle
VISION_MODEL: Qwen/Qwen2.5-VL-32B-Instruct
# 添加向量数据库驱动的路径配置
VECTOR_DB_DRIVER: ./backend/config_files/vector_db_driver/vec0.dll
