MODEL_PATH: C:\Users\ke\Documents\projects\python_projects\SmartImageFinder\models\jina-embeddings-v4 # 我推荐先下载模型到本地，然后将路径替换过来
VECTOR_DB_DRIVER_DIR: ./backend/config/vector_db_driver # 向量数据库驱动目录，系统会自动选择适合当前平台的驱动
EMBEDDING_DIMENSION: 2048
UPLOAD_DIR: ./data/images # 上传的图片存放目录
TEMP_DIR: ./data/temp # 临时文件存放目录
DB_PATH: ./data/db/smartimagefinder.db # 数据库路径
TEXT_VECTOR_CACHE_DIR: ./data/caches/text_vector_cache
IMAGE_VECTOR_CACHE_DIR: ./data/caches/image_vector_cache
USE_CACHE: true # 是否使用缓存
MAX_CACHE_SIZE_GB: 1.5
OPENAI_API_KEY: # 填入你的OpenAI API密钥 
OPENAI_API_BASE: https://open.bigmodel.cn/api/paas/v4/ # 如果需要换成其他API服务商，请修改此处
CHAT_MODEL: glm-4-flash # 聊天模型的名称
VISION_MODEL: glm-4v-flash # 当前使用的视觉模型的名称
AVAILABLE_VISION_MODELS: # 可用的视觉模型列表,可以自己加，只要对应的厂商支持
- glm-4v-flash
HOST: 0.0.0.0 # 这里不要动
PORT: 10050 # 后端的端口号


